name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - ".idea"
      - ".vscode"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build App
        run: npm run build:dir
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: easy-kit-maker-macos
          path: release/
          retention-days: 5
